### ISSUE TITLE
Implement Fixed Height for Card Text and Clamp Overflowing Text

### ISSUE THREAD

**Issue by o-david** [wisdommichaels/A-Traveling-Agency#1]
## Description:

Currently, the card text varies in height based on the amount of text content, leading to an inconsistent layout. To enhance the visual uniformity and user experience, we need to implement a fixed height for the card text. Any text that exceeds this height should be clamped and followed by an ellipsis to indicate overflow.

## Steps to Reproduce:

Navigate to the card component display.
Observe the cards with varying amounts of text content.
Notice the inconsistent heights of the cards.
Expected Behavior:
All cards should have a uniform height, regardless of the amount of text content. Overflowing text should be clamped, with an ellipsis indicating that there is more text that is not visible.

### Actual Behavior:
Cards currently have varying heights based on the text content, leading to an inconsistent layout.

## Proposed Solution:

Set a fixed height for the card text container.
Use CSS to clamp the text that exceeds the fixed height. Example implementation:
* css
Copy code
```
.card-text {
    height: 5lh; /* Set the desired fixed height */
    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 3; /* Number of lines to show */
    -webkit-box-orient: vertical;
}
```
Additional Context:
This change will help maintain a clean and uniform layout, especially in grids or lists of cards, improving the overall user experience.

**Comment by wisdommichaels** [comment]
Thank your sir

**Comment by wisdommichaels** [comment]
the issue has been fixed sir thanks for the assist
